name: Test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(vars.SERVICE_NAME_TO_API_KEY_MAP) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print values
        run: |
          echo "${{ matrix.entry.service }}"
          echo "${{ matrix.entry.apiKey }}"
          echo "${{ secrets[matrix.entry.apiKey] }}"
