name: Test

on:
  push

jobs:
  create-services-matrix:
    name: Create services matrix
    runs-on: ubuntu-latest
    outputs:
        services: ${{ steps.create-services-matrix.outputs.services }}
    steps:
      - name: Create services matrix
        run: |
          SERVICES='[
            {
              "service": "foo",
              "apiKeySecret": "API_KEY_FOO"
            },
            {
              "service": "bar",
              "apiKeySecret": "API_KEY_BAR"
            }
          ]'
          echo services=$SERVICES >> $GITHUB_OUTPUT

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(needs.create-services-matrix.outputs.services) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print values
        run: |
          echo "${{ matrix.entry.service }}"
          echo "${{ matrix.entry.apiKeySecret }}"
          echo "${{ secrets[matrix.entry.apiKeySecret] }}"
